server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/fraud
    username: pourya
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true